ProjectExpedia/ProjectExpedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('', include('userforms.urls')),
    path('', include('vehiclelist.urls')),
    path('search', views.search_view, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectExpedia/userforms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name="login_view"),
    path('register/', views.register_view, name="register_view"),
    path('logout/', views.logout_view, name="logout_view"),
]

ProjectExpedia/vehiclelist/urls.py
from django.urls import path
from . import views

app_name = 'vehiclelist'

urlpatterns = [
    path('vehicles/', views.vehicle_list, name='vehicle_list'),
    path('vehicle_detail/<int:vehicle_id>', views.vehicle_detail, name='vehicle_detail'),
    path('location/<int:location_id>', views.location_list_view, name='location_list'),
]

ProjectExpedia/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />

    <title>
        {% block title %}
            Expeda Clone v1
        {% endblock %}
    </title>
</head>
<body class="">
    
<nav class="bg-white border-gray-200 dark:bg-gray-900 shadow py-4 mb-2">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://www.expedia.com/_dms/header/logo.svg?locale=en_US&siteid=1&2&6f9ec7db" class="h-8" alt="Flowbite Logo" />
            <span class=" text-xs font-light whitespace-nowrap dark:text-gray-100 text-gray-300">Clone v1</span>
        </a>
        <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Shop Travel
                </a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'admin:index' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Admin |
                </a>
            </li>
            <li>
                {{user|capfirst}}
            </li>
            <li>
                <a href="{% url 'logout_view' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    | Log out
                </a>
            </li>
            {% else %}
            <li>
            <a href="{% url 'login_view' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                Sign In
            </a>
            </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

{% block content %}
    Expedia Clone .v1
{% endblock %}

</body>
</html>

ProjectExpedia/templates/index.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% load static %}

{% block title %}
    Expedia Clone .v1
{% endblock %}

{% block content %}
    <section class="bg-white dark:bg-gray-900 my-10">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto px-4 rounded-2xl border">
            <div class="border-b border-b-1 my-5 mt-0 max-w-screen-xl w-full">
                <ul class="flex justify-center space-x-4 my-2">
                    <li><a href="#" class="hover:text-blue-500">Cars</a></li>
                    <li><a href="#" class="hover:text-blue-500">Stays</a></li>
                    <li><a href="#" class="hover:text-blue-500">Flights</a></li>
                    <li><a href="#" class="hover:text-blue-500">Packages</a></li>
                    <li><a href="#" class="hover:text-blue-500">Things to do</a></li>
                    <li><a href="#" class="hover:text-blue-500">Cruises</a></li>
                </ul>
            </div>

            <div class="my-5 mt-0 max-w-screen-xl w-full">
                <form class="max-w-screen-xl w-full mx-auto" method="post" action="{% url 'search' %}" >
                    
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">Search</button>

                        
                    
                    
                    <div class="grid grid-cols-6 gap-5">
                        <!-- Pick-up-->
                        <!-- <div class="relative">
                            <label for="default-search" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Pick-up:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                                </svg>
                            </div>
                            <input type="search" id="default-search" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Pick-up" required />
                        </div> -->

                        <!-- Same as pick-up -->
                        <!-- <div class="relative">
                            <label for="default-search" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Same as pick-up:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                                </svg>
                            </div>
                            <input type="search" id="default-search" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Same as pick-up" required />
                        </div> -->

                        <!-- Pick-up date -->
                        <!-- <div class="relative">
                            <label for="default-datepicker" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Pick-up date:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                </svg>
                            </div>
                            <input datepicker id="default-datepicker2" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select pick-up date">
                        </div> -->

                        <!-- Return date -->
                        <!-- <div class="relative">
                            <label for="default-datepicker" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Return date:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                </svg>
                            </div>
                            <input datepicker id="default-datepicker" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select  return date">
                        </div> -->

                        <!-- Select time -->
                        <!-- <div class="relative">
                            <label for="time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select time:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
                                </svg>
                            </div>
                            <input type="time" id="time" class="bg-gray-50 border leading-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" min="09:00" max="18:00" value="00:00" required />
                        </div> -->

                        <!-- Select return time -->
                        <!-- <div class="relative">
                            <label for="time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select return time:</label>
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none top-6">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm11-4a1 1 0 1 0-2 0v4a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414L13 11.586V8Z" clip-rule="evenodd"/>
                                </svg>
                            </div>
                            <input type="time" id="time" class="bg-gray-50 border leading-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" min="09:00" max="18:00" value="00:00" required />
                        </div> -->

                        <!-- Submit Button -->
                        <!-- <div>
                            <label for="submit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> &nbsp</label>
                            <button type="submit" class="text-white end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none w-full focus:ring-blue-300 font-medium rounded-2xl text-sm px-6 p-4 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
                        </div> -->
                    </div>
                    
                </form>
            </div>

        </div>
    </section>
  

    
    <section class="bg-white dark:bg-gray-900 my-10">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto px-4 rounded-2xl border">

            {% include 'vehiclelist/vlist.html' with vehicles=vehicles %}
            
        </div>
    </section>
    {% endblock %}

  
</body>
</html>

ProjectExpedia/templates/search.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}
    Expedia Clone .v1
{% endblock %}

{% block content %}
<form class="max-w-screen-xl w-full mx-auto" method="post" action="{% url 'search' %}">
                    
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Search</button>
</form>
{% endblock %}

ProjectExpedia/templates/search_result.html
{% extends 'base.html' %}

{% load math_extras %}


{% block title %}
    Expedia Clone .v1 Search Result
{% endblock %}
{% block content %}


<section class="flex mx-auto my-10 justify-center max-w-screen-xl">

  <div class="w-4/5 px-4 rounded-2xl border mr-10">
    <div class="w-full max-w-screen-xl flex flex-wrap items-center justify-between p-4 text-right">
      <div><h2 class="text-2xl font-bold tracking-tight text-gray-900">Search Result</h2></div>
      
    </div>
    <div class="mt-6 w-full">
      
      {% for vehicle in vehicles %}
      <div class="group relative flex my-4 border-b border-b-1 ">
          <div class="aspect-w-1 flex overflow-hidden rounded-md lg:aspect-none group-hover:opacity-75 mr-10">
              {% if vehicle.imagefield %}
                <img src="{{ vehicle.imagefield.url }}" alt="" class="" style="width: 150px; height:auto;">
                {% else %}
                <img src="{% static 'images/placeholder.png' %}" alt="Placeholder Image" style="width: 150px; height:auto;">
              {% endif %}
          </div>
          <div class="mt-4 flex justify-between md:flex-row flex-col flex justify-between items-start w-full pb-8 space-y-4 md:space-y-0">
            <div>
              <h3 class="text-sm text-gray-700">
                <a href="/vehicle_detail/{{vehicle.id}}">
                  <span class=""></span>
                  {{vehicle.year}} {{vehicle.brand}}
                </a>
              </h3>
              <p class="mt-1 text-sm text-gray-500">{{vehicle.model}}</p>
            </div>
            <div><p class="text-sm font-medium text-gray-900">${{vehicle.price}}</p></div>
            <div><p class="text-sm font-medium text-gray-900">Pay at Pick up</p></div>
            <div>{% if vehicle.free_cancellation %}<p class="text-sm font-medium text-gray-900">Free Cancellation</p>{% endif %}</div>
            {% if vehicle.unlimited_milage %}
              <div><p class="text-sm font-medium text-gray-900">Unlimited Mileage</p></div>
            {% else %}
              <div><p class="text-sm font-medium text-gray-900">200 miels per day</p></div>
            {% endif %}
            {% if vehicle.rating %}<p class="text-sm font-medium text-gray-900">{{vehicle.rating}}</p>{%endif%}
            <div><p class="text-xl font-bold text-red-600">${{vehicle.price|multiply:reservation_days}}</p></div>
            <div>
              <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Reserve 
                <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                </svg>
              </button>
            </div>
            
            <!-- {% for code, name in getlax_us %}
            <p class="text-sm font-medium text-gray-900">${{name}}</p>
            {% endfor %} -->
          </div>
        </div>
        {% endfor %}
      </div>
  </div>

  <div class="w-1/5 px-4 rounded-2xl border py-4">
    <div>
      <div><h2 class="text-2xl font-bold tracking-tight text-gray-900">Search Result</h2></div>
      

        <dl class="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700">
          <div class="flex flex-col pb-3">
              <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Pick-up Location:</dt>
              <dd class="text-lg font-semibold"><a href="{% url 'vehiclelist:location_list' pickup_location.id %}"> {{ pickup_location.location }}</a></dd>
          </div>
          <div class="flex flex-col py-3">
            <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Pick-up Date:</dt>
            <dd class="text-lg font-semibold">{{ pickup_date }}</dd>
          </div>
          <div class="flex flex-col py-3">
              <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Pick-up Time:</dt>
              <dd class="text-lg font-semibold">{{ pickup_time }}</dd>
          </div>
          <div class="flex flex-col pt-3">
              <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Drop-off Date:</dt>
              <dd class="text-lg font-semibold">{{ return_date }}</dd>
          </div>
          <div class="flex flex-col pt-3">
            <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Drop-off Time:</dt>
            <dd class="text-lg font-semibold">{{ return_time }}</dd>
          </div>
          <div class="flex flex-col pt-3">
            <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Trip Days:</dt>
            <dd class="text-lg font-semibold">{{reservation_days}}</dd>
          </div>
        </dl>


    </div>

  </div>

</section>
{% endblock %}






  